backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/folderImages'
public_folder: '/img'

collections:
  - name: 'landingPage'
    label: 'section'
    folder: 'content/landingPage'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Alt', name: 'alt', widget: 'string' }
      - { label: 'ContentId', name: 'contentId', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
