backend:
  name: git-gateway
  branch: main

media_folder: '/src/assets/folderImages'
public_folder: ''

collections:
  - name: 'landingPage'
    label: 'section'
    folder: 'content/landingPage'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image' , required: false}
      - { label: 'Alt', name: 'alt', widget: 'string', required: false }
      - { label: 'ContentId', name: 'contentId', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' , required: false}
